export const STANDARD_LOG_SCHEMA = {
  "$schema": "http://json-schema.org/draft-06/schema#",
  "type": "object",
  "properties": {
    "key_1": { "type": [ "string", "null" ] },
    "key_1_value": { "type": [ "string", "null" ] },
    "key_2": { "type": [ "string", "null" ] },
    "key_2_value": { "type": [ "string", "null" ] },
    "key_3": { "type": [ "string", "null" ] },
    "key_3_value": { "type": [ "string", "null" ] },
    "numkey_1": { "type": [ "string", "null" ] },
    "numkey_1_value": { "type": [ "number", "null" ] },
    "numkey_2": { "type": [ "string", "null" ] },
    "numkey_2_value": { "type": [ "number", "null" ] },
    "numkey_3": { "type": [ "string", "null" ] },
    "numkey_3_value": { "type": [ "number", "null" ] },
    "numkey_4": { "type": [ "string", "null" ] },
    "numkey_4_value": { "type": [ "number", "null" ] },
    "numkey_5": { "type": [ "string", "null" ] },
    "numkey_5_value": { "type": [ "number", "null" ] },
    "numkey_6": { "type": [ "string", "null" ] },
    "numkey_6_value": { "type": [ "number", "null" ] },
    "customer_request_id": { "type": [ "string", "null" ] },
    "provider_id": { "type": [ "string", "null" ] },
    "transaction_id": { "type": [ "string", "null" ] },
    "customer_id": { "type": [ "string", "null" ] },
    "lead_id": { "type": [ "string", "null" ] },
    "method_name": { "type": [ "string", "null" ] },
    "url": { "type": [ "string", "null" ] },
    "status": { "type": [ "string", "null" ] },
    "uuid": { "type": [ "string", "null" ] },
    "error_id": { "type": [ "string", "null" ] },
    "api_name": { "type": [ "string", "null" ] },
    "api_path": { "type": [ "string", "null" ] },
    "api_time": { "type": [ "number", "null" ] },
    "timestamp": { "type": [ "string", "null" ] },
    "file_name": { "type": [ "string", "null" ] },
    "container_id": { "type": [ "string", "null" ] },
    "task_id": { "type": [ "string", "null" ] },
    "container_ip": { "type": [ "string", "null" ] },
    "service_port": { "type": [ "number", "null" ] },
    "container_port": { "type": [ "number", "null" ] },
    "log_type": { "type": [ "string", "null" ] },
    "service_name": { "type": [ "string", "null" ] },
    "success": { "type": [ "string", "null" ] },
    "user_agent": { "type": [ "string", "null" ] },
    "device_name": { "type": [ "string", "null" ] },
    "device_id": { "type": [ "string", "null" ] },
    "version_name": { "type": [ "string", "null" ] },
    "version_code": { "type": [ "string", "null" ] },
    "build_version": { "type": [ "string", "null" ] },
    "client_id": { "type": [ "string", "null" ] },
    "message": { "type": [ "string", "null" ] },
    "error_message": { "type": [ "string", "null" ] },
    "error_stack": { "type": [ "string", "null" ] },
    "error_payload": { "type": [ "string", "null" ] },
    "error_type": { "type": [ "string", "null" ] },
    "error": { "type": [ "string", "null" ] }
  },
  "additionalProperties": false
}